version: '3.8'

services:
  smeadmin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: smeadmin
    restart: unless-stopped
    environment:
      - NODE_ENV=production
